import { createContext } from "react";

export const DasboardData = createContext({
  pageNumber: 0,
  handlePageNumber: () => {},
  drawerOpen: false,
  setDrawerOpen: () => {},
  coins: [],
  setCoins: () => {},
  loading: false,
  setLoading: () => {},
  allMarekts: [],
  setAllMarkets: () => {},
  javascript: 0,
  html: 0,
  css: 0,
  nextJs: 0,
  reactJs: 0,
  reactNA: 0,
  git: 0,
  scss: 0,
  redux: 0,
  mui: 0,
  graph: 0,
  boot: 0,
  setJavascript: () => {},
  setHtml: () => {},
  setCss: () => {},
  setNextJs: () => {},
  setReactJs: () => {},
  setReactNA: () => {},
  setGit: () => {},
  setScss: () => {},
  setRedux: () => {},
  setMui: () => {},
  setGraph: () => {},
  setBoot: () => {},
});
